# Generated by Django 5.0.6 on 2024-06-19 07:20

import apps.orders.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=apps.orders.models.generate_order_id,
                        editable=False,
                        max_length=30,
                        verbose_name="order ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="total",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "indexes": [
                    models.Index(
                        fields=["order_id"], name="orders_orde_order_i_205064_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="orders_orde_custome_59b6fb_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="orders_orde_created_0e92de_idx"
                    ),
                ],
            },
        ),
    ]
