# Generated by Django 5.0.6 on 2024-06-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_created_at_alter_order_customer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_order_i_205064_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_custome_59b6fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_created_0e92de_idx",
        ),
    ]
